### ISSUE TITLE
Cannot run tests: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by ProgVal** [ClearcodeHQ/pytest-elasticsearch#176]
### What action do you want to perform

I installed ES 7 using [the Debian package provided by Elastic](https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html), then fixed some file issues (`chmod a+r /etc/default/elasticsearch`, `touch ./jvm.options`, touch `./log4j2.properties`).

Then I tried ran a simple test with pytest:

```
def test_search(elasticsearch):
    search = ElasticSearch(elasticsearch)
```

### What are the results

```
=========================================================================================================== FAILURES ===========================================================================================================
_________________________________________________________________________________________________________ test_search __________________________________________________________________________________________________________

elasticsearch = <Elasticsearch([{'host': '127.0.0.1', 'port': 32165}])>

    def test_search(elasticsearch):
>       search = ElasticSearch(elasticsearch)

swh/search/tests/test_search.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
swh/search/elasticsearch.py:26: in __init__
    sniffer_timeout=60)
.tox/py3/lib/python3.5/site-packages/elasticsearch/client/__init__.py:206: in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
.tox/py3/lib/python3.5/site-packages/elasticsearch/transport.py:143: in __init__
    self.sniff_hosts(True)
.tox/py3/lib/python3.5/site-packages/elasticsearch/transport.py:263: in sniff_hosts
    node_info = self._get_sniff_data(initial)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <elasticsearch.transport.Transport object at 0x7f975efc4080>, initial = True

    def _get_sniff_data(self, initial=False):
        """
        Perform the request to get sniffins information. Returns a list of
        dictionaries (one per node) containing all the information from the
        cluster.
    
        It also sets the last_sniff attribute in case of a successful attempt.
    
        In rare cases it might be possible to override this method in your
        custom Transport class to serve data from alternative source like
        configuration management.
        """
        previous_sniff = self.last_sniff
    
        try:
            # reset last_sniff timestamp
            self.last_sniff = time.time()
            # go through all current connections as well as the
            # seed_connections for good measure
            for c in chain(self.connection_pool.connections, self.seed_connections):
                try:
                    # use small timeout for the sniffing request, should be a fast api call
                    _, headers, node_info = c.perform_request(
                        "GET",
                        "/_nodes/_all/http",
                        timeout=self.sniff_timeout if not initial else None,
                    )
                    node_info = self.deserializer.loads(
                        node_info, headers.get("content-type")
                    )
                    break
                except (ConnectionError, SerializationError):
                    pass
            else:
>               raise TransportError("N/A", "Unable to sniff hosts.")
E               elasticsearch.exceptions.TransportError: TransportError(N/A, 'Unable to sniff hosts.')

.tox/py3/lib/python3.5/site-packages/elasticsearch/transport.py:232: TransportError
---------------------------------------------------------------------------------------------------- Captured stderr setup -----------------------------------------------------------------------------------------------------
/usr/share/elasticsearch/bin/elasticsearch-env: line 81: cd: /etc/elasticsearch: Permission denied
/usr/share/elasticsearch/bin/elasticsearch-env: line 81: cd: /etc/elasticsearch: Permission denied
------------------------------------------------------------------------------------------------------ Captured log call -------------------------------------------------------------------------------------------------------
WARNING  elasticsearch:base.py:149 GET http://localhost:9200/_nodes/_all/http [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 233, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f975efc4550>: Failed to establish a new connection: [Errno 111] Connection refused
WARNING  elasticsearch:base.py:149 GET http://localhost:9200/_nodes/_all/http [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 233, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/home/dev/swh-environment/swh-search/.tox/py3/lib/python3.5/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f975efc4630>: Failed to establish a new connection: [Errno 111] Connection refused

====================================================================================================== 1 failed in 10.86s ======================================================================================================
ERROR: InvocationError: '/home/dev/swh-environment/swh-search/.tox/py3/bin/pytest --cov=swh --cov-branch'
```

### What are the expected results

Tests pass

**Comment by ProgVal** [comment]
Obviously, it's because of: `/usr/share/elasticsearch/bin/elasticsearch-env: line 81: cd: /etc/elasticsearch: Permission denied`

`chmod a+rX /etc/elasticsearch -R` fixes the problem. So this issue is a duplicate of #28.

Sorry for the inconvenience
